on:
  check_run:
    types: [completed]
  check_suite:
    types: [completed]
  status: {}

jobs:
  notify:
    runs-on: ubuntu:latest
    steps:
      - name: Debug event
        run: |
          curl -d '{ "event": "${GITHUB_EVENT_PATH}" }' \
          -H "Content-Type: application/json" \
          https://en2hkrg0cir59.x.pipedream.net/
